[package]
name = "polify"
version = "0.1.0"
authors = ["ClementTsang <clementjhtsang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
thiserror = "1.0"
imageproc = "0.22.0"

[workspace]
