[package]
name = "polify"
version = "0.1.0"
authors = ["ClementTsang <clementjhtsang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.23.12", default-features = false, features = [ "jpeg", "png", "webp", "bmp" ] } 
thiserror = "1.0"
imageproc = "0.22.0"
# wasm-bindgen = "0.2"
rand = "0.8"
delaunator = "0.2.0"

[lib]
# crate-type = ["cdylib"]

[workspace]
members = [
    "examples/simple_test",
]

[profile.release]
# debug = true
lto = true
# opt-level = "s"