//! Errors that polify may encounter.

/// An error generated by polify.
#[derive(thiserror::Error, Debug)]
pub enum PolifyError {
    /// An I/O error.
    #[error("io error")]
    Io(#[from] std::io::Error),
    /// An error from the image crate.
    #[error("image error")]
    Image(#[from] image::ImageError),
    #[error("file already exists at {0}")]
    /// An error if a file already exists at the given save location.
    FileAlreadyExists(String),
    #[error("no triangulation exists for this input")]
    /// An error formed if triangulation fails.
    Triangulation,
    /// An unknown error.
    #[error("unknown error")]
    Unknown,
}

/// A `Result` type with a [`PolifyError`].
pub type Result<T> = std::result::Result<T, PolifyError>;
